apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    app: nginx
    env: dev
spec:
  selector:
    app: nginx-nodeport
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32767 #Podemos escolher de 30000 - 32767
  type: NodePort
