apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: meu-daemonset
  name: meu-daemonset
spec:
  selector:
    matchLabels:
      app: meu-daemonset
  template:
    metadata:
      labels:
        app: meu-daemonset
    spec:
      hostNetwork: true
      containers:
      - name: meu-daemonset
        image: prm/node-exporter:latest
        ports:
        - containerPort: 9100
          hostPort: 9100
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
