apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-teste
    env: dev
  name: pod-teste
spec:
  containers:
  - name: container-teste
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
         name: secret-teste
         key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
         name: secret-teste
         key: password
