apiVersion: v1
kind: Pod
metadata:
  labels:
    run: meu-pod
  name: meu-pod
spec:
  containers:
  - image: nginx
    name: meu-nginx
    volumeMounts:
    - mountPath: /mnt/web/
      name: volume-web
    resources:
      limits:
        memory: 128Mi
        cpu: "0.3"
      requests:
        memory: 64Mi
        cpu: "0.1"
  - image: busybox
    name: meu-app
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo ola mundo; sleep 120;done"]
    volumeMounts:
    - mountPath: /mnt/app/
      name: volume-app
    resources:
      limits:
        memory: 128Mi
        cpu: "0.3"
      requests:
        memory: 64Mi
        cpu: "0.1"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: volume-web
      emptyDir:
        sizeLimit: 32Mi
    - name: volume-app
      emptyDir:
        sizeLimit: 32Mi
